### ISSUE TITLE
Приложение не запускается

### ISSUE THREAD

**Issue by afloemkis** [netology-code/and2-homeworks#3]
Создала первое приложение на adnroid studio, просто автоматически, ничего не добавляла. Выбрала девайс для эмулятора. Запускаю приложение и получаю ошибку Error running 'app': Timed out after 300seconds waiting for emulator to come online. 

Окружение: ОС (версия и разрядность), версия Kotlin, ссылка на исходники проекта на GitHub
Windows 10 Pro 64-разрядная операционная система, процессор x64
Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz 6,00 ГБ (доступно: 5,87 ГБ)
cottin plugin version 223-1.8.0-release-345-AS8836.35.2231.10406996

в logcat пусто

**Comment by amostyaev** [comment]
Здравствуйте! 

Попробуйте запустить эмулятор через терминал, там должна показаться диагностика.

Сначала нужно перейти в директорию, где лежит файл emulator.exe, это в Android SDK
Потом сделать emulator -list-avds, там будет имя эмулятора. Затем запустить с этим именем, подставить его вместо имя_эмулятора. Полная инструкция тут

https://developer.android.com/studio/run/emulator-commandline

**Comment by afloemkis** [comment]
Артем, здравствуйте! Спасибо
При запуске emulator.exe (в т.ч. от администратора) мелькает окошко и
пропадает. Видимо, в этом и проблема, похожее мелькание было и при запуске
из андроид-студии.

Что делать? пока ничего не нагуглила подходящего

ср, 2 авг. 2023 г., 11:12 Artem Mostyaev ***@***.***>:

**Comment by amostyaev** [comment]
Нужно запускать emulator.exe из терминала, не из проводника.

**Comment by afloemkis** [comment]
ага, поняла. Тогда вот

C:\Users\Artem\AppData\Local\Android\Sdk\emulator>emulator -list-avds
Pixel_3a_API_34_extension_level_7_x86_64
Pixel_7_API_30

C:\Users\Artem\AppData\Local\Android\Sdk\emulator>emulator -avd-Pixel_7_API_30
INFO    | Android emulator version 32.1.14.0 (build_id 10330179) (CL:N/A)
ERROR   | No AVD specified. Use '@foo' or '-avd foo' to launch a virtual device named 'foo'

**Comment by amostyaev** [comment]
Вторая команда должна быть 

emulator -avd Pixel_7_API_30

**Comment by afloemkis** [comment]
класс, заработал! И теперь можно его закрыть и через android studio попробовать?

**Comment by amostyaev** [comment]
По идее, Android Studio прямо в него теперь будет устанавливать. Можно сначала так попробовать. А потом попробовать закрыть и запустить из студии.

**Comment by afloemkis** [comment]
супер, спасибо большое. Может, я наконец выполню задание )
